#!/bin/bash

if [ $# == 0 ]
then
	echo "Try wifi --help for more information"
	exit 1
fi
if [ $1 == "--help" ]
then
	cat help.txt
	exit 1
fi
if [ $1 == "list" ]
then 
	if [ $(nmcli radio wifi) == "enabled" ]
	then
		nmcli dev wifi list > /tmp/wifi.txt
		cat /tmp/wifi.txt
		rm /tmp/wifi.txt
	else 
		echo "Wifi is disabled"

	fi
fi
if [ $1 == "connect" ]
then
	nmcli dev wifi connect $2
fi
if [ $1 == "on" ]
then
	if [ $(nmcli radio wifi) == "enabled" ]
	then
		echo "Wifi is already enabled"
	else 
		nmcli radio wifi on
	fi
fi
if [ $1 == "off" ]
then 
	if [ $(nmcli radio wifi) == "disabled" ]
	then 
		echo "Wifi is already disabled"
	else 
		nmcli radio wifi off
	fi
fi
if [ $1 == "pass" ]
then 
	if [ $(nmcli radio wifi) == "disabled" ]
        then
		echo "Wifi is already disabled"
        else
                nmcli dev wifi show-password

        fi
fi
